# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

### TUTORIAL:
###  We want to separate the Rest controllers from our Web controllers
###  All our Rest calls should be prefixed by /api

fos_rest:
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
