<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRhZlNj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRhZlNj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRhZlNj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRhZlNj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXRhZlNj\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XRhZlNj',
    'container.build_id' => '2399632b',
    'container.build_time' => 1546442465,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRhZlNj');
